routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::middleware('auth')->group(function(){
    // Rutas Web
	Route::get('/',                 			'WebController@index');
    Route::get('/directory',					'Web\DirectoryController@index')->name('directory');
    Route::post('/directory',					'Web\DirectoryController@search')->name('directory.search');
    Route::post('/directory/filter',		'Web\DirectoryController@filter')->name('directory.filter');
    Route::get('/ranking',						'Web\RankingController@index')->name('ranking');
    Route::get('/programs',						'Web\ProgramController@index');
    Route::get('/programs/{id}',				'Web\ProgramController@show');
    Route::get('/contact',						'WebController@contact');
    Route::get('/mall/product/{id}',          	'Web\StoreController@product') -> name('store.product');
    Route::get('/mall/market/{market}',         'Web\StoreController@market') -> name('store.market');
    Route::get('/mall/{category}',             	'Web\StoreController@category') -> name('store.category');
    Route::get('/mall/{category}/{subcategory}','Web\StoreController@subcategory') -> name('store.subcategory');
	Route::get('/mall',             			'Web\StoreController@index') -> name('store.index');
	Route::post('/mall',             			'Web\StoreController@filter') -> name('store.filter');
	Route::get('/shopping/branches/{branch_id}','WebController@branchCart');

	//Others routes
	Route::get('/politics', function() {
	    return view('web.others.politics');
	});
	Route::get('/terms', function() {
	    return view('web.others.terms');
	});
	Route::get('/faq', function() {
	    return view('web.others.faq');
	});

	//My account routes
	Route::get('/my-account/orders',      'Web\MyAccountController@orders')->name('my-account.orders');
    Route::get('/my-account/orders/{id}',      'Web\MyAccountController@order')->name('my-account.order');
    Route::post('/my-account/change-image/{id}',      'Web\MyAccountController@changeImage')->name('my-account.change-image');
    Route::get('/my-account/configuration',      'Web\MyAccountController@configuration')->name('my-account.configuration');
    Route::post('/my-account/change-password',      'Web\MyAccountController@changePassword')->name('my-account.change-password');
	Route::post('/my-account/edit-branch',      'Web\MyAccountController@updateBranch')->name('my-account.edit-branch');
    Route::get('/my-account',      'Web\MyAccountController@index')->name('my-account.index');
	Route::post('/my-account',      'Web\MyAccountController@update')->name('my-account.update');
	Route::post('/my-account/imessages/response/destroy',      'Web\MessageController@responseDestroy')->name('response.destroy');
	Route::post('/my-account/imessages/response/{id}',      'Web\MessageController@response')->name('imessage.response');
	Route::resource('/my-account/imessages',      'Web\MessageController');


    //Cart routes
    Route::get('/shopping',        	'Web\CartController@show')->name('cart.show');
    Route::post('/shopping/add-product/{id}',        	'Web\CartController@add')->name('cart.add');
    Route::get('/shopping/delete-product/{id}',        	'Web\CartController@delete')->name('cart.delete');
    Route::post('/shopping/update-products',        	'Web\CartController@update')->name('cart.update');
    Route::post('/shopping/destroy',        	'Web\CartController@destroy')->name('cart.destroy');
    Route::post('/shopping/order',        	'Web\CartController@generateOrder')->name('cart.order');

});


Route::prefix('admin')->group( function(){
	Route::post('/images/destroy', 						'Admin\AdminController@imageDestroy')->name('images.destroy');
	Route::post('/images/update', 						'Admin\AdminController@imageUpdate')->name('images.update');
	Route::get('/login',					'Admin\LoginController@showLoginForm')->name('admin.login');
	Route::post('/login',					'Admin\LoginController@login')->name('admin.login.submit');
	Route::post('/logout',					'Admin\LoginController@logout')->name('admin.logout');
	Route::post('password/email',					'Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	Route::get('password/reset',					'Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
	Route::post('password/reset',					'Admin\ResetPasswordController@reset');
	Route::get('password/reset/{token}',	'Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');

	Route::middleware('auth:user')->group(function(){

		Route::post('/profile/change-password', 'Admin\ProfileController@changePassword')->name('profile.change-password');
		Route::get('/lists/state/{id}', 		'Admin\ListController@getState');
		Route::get('/lists/city/{id}', 			'Admin\ListController@getCity');
		Route::post('guides/store/{id}',     	'Admin\GuideController@store')->name('guides.store');
		Route::get('/', 						'Admin\AdminController@index')->name('admin.dashboard');
		Route::get('/logs', 					'\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
		Route::get('/objetives/create/{id}',    'Admin\ObjetiveController@newcreate');
		Route::get('/products/create/{id}',     'Admin\ProductController@newCreate');
		Route::post('/members/import',          'Admin\MemberController@import')->name('members.import');
		Route::get('/members/filter',      		'Admin\MemberController@filter')->name('members.filter');
		Route::post('/departments/import',		'Admin\DepartmentController@import')->name('departments.import');
		Route::post('/branches/import',     	'Admin\BranchController@import')->name('branches.import');
		Route::get('/transactions/filter',      'Admin\TransactionController@filter')->name('transactions.filter');
		Route::post('/payload/insert-file',      	'Admin\PayloadController@InsertFile')->name('payload.insert_file');
        Route::get('/payload/filter',      		'Admin\PayloadController@filter')->name('payload.filter');
        Route::post('/groups/filter',      		'Admin\GroupController@filter')->name('groups.filter');
		Route::get('/orders/filter',      		'Admin\OrderController@filter')->name('orders.filter');
		Route::put('/orders/status/{id}',       'Admin\OrderController@status')->name('orders.status');
		Route::get('/orders/refund-create/{id}','Admin\OrderController@refund_create')->name('orders.refund-create');
		Route::post('/orders/refund-store/{id}','Admin\OrderController@refund_store')->name('orders.refund-store');
		Route::get('/accounts/filter/{id}',     'Admin\AccountController@filter')->name('accounts.filter');
		Route::get('/programs/filter',          'Admin\ProgramController@filter')->name('programs.filter');
		Route::get('/picking',          'Admin\PickingController@index');
		Route::get('/reports',          'Admin\ReportController@index');
		Route::get('/reports/inventory-output',          'Admin\ReportController@inventoryOutput');
		Route::get('/reports/exchange-item',          'Admin\ReportController@exchangeItem');
		Route::get('/reports/exchange-user',     'Admin\ReportController@exchangeUser');
		Route::get('/reports/exchange-item/filter',   'Admin\ReportController@exchangeFilter')->name('exchange-item.filter');
		Route::get('/reports/exchange-user/filter',   'Admin\ReportController@exchangeUserFilter')->name('exchange-user.filter');
		Route::get('/reports/contribution-exchange',   'Admin\ReportController@reportContributionAndExchange');
		Route::get('/reports/contribution-exchange/filter',   'Admin\ReportController@reportContributionAndExchangeFilter')->name('contribution-exchange.filter');
		Route::get('/reports/inventory-output/filter',          'Admin\ReportController@inventoryOutputFilter')->name('reports.inventory-output.filter');
		Route::resource('/consolidated',        'Admin\AccountController');
		Route::resource('/transactions',        'Admin\TransactionController');
		Route::resource('/payload',             'Admin\PayloadController');
		Route::resource('/accounts',            'Admin\AccountController');
		Route::post('/profile/image-change/{id}',		'Admin\ProfileController@imageChange');
		Route::resource('/profile',				'Admin\ProfileController');
		Route::resource('/users', 				'Admin\UserController');
		Route::resource('/roles', 				'Admin\RoleController');
		Route::resource('/clubs', 				'Admin\ClubController');
		Route::resource('/brands', 		  		'Admin\BrandController');
		Route::resource('/categories', 			'Admin\CategoryController');
		Route::resource('/subcategories', 		'Admin\SubcategoryController');
		Route::resource('/offers', 				'Admin\OfferController');
		Route::resource('/affiliates', 			'Admin\AffiliateController');
		Route::resource('/parents-products', 	'Admin\ParentProductController');
		Route::resource('/inventory', 			'Admin\InventoryController');
		Route::resource('/products', 			'Admin\ProductController');
		Route::resource('/agents', 				'Admin\AgentController');
		Route::resource('/orders', 				'Admin\OrderController');
		Route::resource('/programs', 			'Admin\ProgramController');
		Route::resource('/groups', 				'Admin\GroupController');
		Route::resource('/objetives', 			'Admin\ObjetiveController');
		Route::resource('/members', 			'Admin\MemberController');
		Route::resource('/branches',     		'Admin\BranchController');
		Route::resource('departments',     		'Admin\DepartmentController');
		Route::post('/messages/change-status',      'Admin\MessageController@updateStatus')->name('message.change-status');
		Route::post('/messages/response/destroy',      'Admin\MessageController@responseDestroy')->name('responses.destroy');
		Route::post('/messages/response/{id}',      'Admin\MessageController@response')->name('message.response');

resources/views/admin/parents_products/index.blade.php
@extends('layouts.admin.default')

@section('title', 'Productos')
@section('styles')
    <link rel="stylesheet" type="text/css" href="{{asset('core-plus-theme/css/custom_css/dashboard1.css')}}" />
    <link rel="stylesheet" type="text/css" href="{{ asset('core-plus-theme/vendors/datatables/css/dataTables.bootstrap.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ asset('core-plus-theme/css/advbuttons.css') }}"/>
@stop
@section('content')
    <!-- Content Header (Page header) -->
    <header class="header-page">
        <div class="header-data">
            <h1>@yield('title') <small>- Items</small></h1>
        </div>
    </header>
    @include('flash::message')
	<article class="content">
			<div class="panel filterable">
                <div class="panel-heading clearfix">
                    @if (Auth::user() -> kind == 1)
                        <div class="pull-right">
                            <a class="btn btn-success" href="{{ route('parents-products.create') }}">Nuevo</a>
                        </div>
                    @endif
                </div>
                <div class="panel-body">
                    <table id="table4" class="table table-striped table-hover datatable-asc"  data-toolbar="#toolbar" data-search="true" data-show-refresh="false"
                               data-show-toggle="true" data-show-columns="true" data-show-export="true"
                               data-detail-view="true" data-detail-formatter="detailFormatter"
                               data-minimum-count-columns="2" data-show-pagination-switch="true"
                               data-pagination="true" data-id-field="id" data-page-list="[10, 20,40,ALL]"
                               data-show-footer="false" data-height="503">
                        <thead>
                            <tr>
                                <th>Nombre</th>
                                <th>Modelo</th>
                                <th>Mercado</th>
                                <th>Marca</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($parents_products as $datos)
                                <tr>
                                    <td><a href="{{route('parents-products.show', $datos -> id)}}" class="text-capitalize">{{ $datos -> name }}</a></td>
                                    <td>{{ $datos -> model }}</td>
                                    <td class="text-capitalize">@if ( $datos -> market == 0) Ambos @elseif( $datos -> market == 1) Masculino @else Femenino @endif</td>
                                    <td class="text-capitalize">{{ $datos -> brand }}</td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
	</article>
@stop
@section('scripts')
    <!-- page js -->
    <script type="text/javascript" src="{{ asset('core-plus-theme/vendors/datatables/js/jquery.dataTables.js') }}"></script>
    <script type="text/javascript" src="{{ asset('core-plus-theme/vendors/datatables/js/dataTables.bootstrap.js') }}"></script>
    <script type="text/javascript" src="{{ asset('core-plus-theme/js/custom_js/datatables_custom.js') }}"></script>
    <!-- end page js -->
@endsection

resources/views/admin/parents_products/show.blade.php
@extends('layouts.admin.default')

@section('title', 'Producto')
@section('styles')
    <link rel="stylesheet" type="text/css" href="{{asset('core-plus-theme/css/custom_css/dashboard1.css')}}" />
@stop
@section('content')
    <!-- Content Header (Page header) -->
    <header class="header-page">
        <div class="header-data">
            <h1>@yield('title') <small>- Ver</small></h1>
        </div>
    </header>
    @include('flash::message')
    <article class="content">
        <div class="panel filterable">
            <div class="panel-heading clearfix">
                <div class="pull-left text-center">
                    <h3>Datos principales</h3>
                </div>
                <div class="pull-right text-center">
                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal-delete" >Eliminar</button>
                    <a href="{{route('parents-products.index')}}" type="button" class="btn btn-warning">Atrás</a>
                    <a href="{{route('parents-products.edit', $parent_product -> id)}}" type="button" class="btn btn-primary">Editar</a>
                </div>
            </div>
            <div class="panel-body row">
                <div class="col-md-6">
                    <ul class="panel-list">
                        <li class="row">
                            <div class="col-xs-12 col-sm-12">
                                <p><b>Nombre</b></p>
                                <p>{{ $parent_product -> name }}</p>
                            </div>
                        </li>
                        <li class="row">
                            <div class="col-xs-6 col-sm-4">
                                <p><b>Modelo</b></p>
                                <p>{{ $parent_product -> model }}</p>
                            </div>
                            <div class="col-xs-6 col-sm-6">
                                <p><b>Marca</b></p>
                                <p class="text-capitalize">{{ $parent_product -> brand }}</p>
                            </div>
                        </li>
                        <li class="row">
                            <div class="col-xs-12">
                                <p><b>Descripción</b></p>
                                <p>{!! $parent_product -> description !!}</p>
                            </div>
                        </li>   
                        <h4>Características</h4>
                        <hr>
                        <li class="row">
                            <div class="col-xs-12 col-sm-12">
                                <p><b>Mercado</b></p>
                                <p>{{ $parent_product -> market}}</p>
                            </div>
                            <hr>
                        </li>   
                        <h4>Sub-categorías</h4>
                        <hr>   
                        <li class="row">
                            <div class="col-xs-12">
                                <p><b>Sub Categorías</b></p>
                                @foreach ($parents_products_subcategories as $subcategory)
                                    <p class="text-capitalize label label-primary">{{ $subcategory -> name }}</p>
                                @endforeach
                            </div>
                        </li>
                         <h4>Clubs</h4>
                        <hr>
                        <li class="row">
                            <div class="col-xs-12">
                                <p><b>Clubs</b></p>
                                @foreach ($clubs_parents_products as $club)
                                        <p class="text-capitalize label label-primary">{{ $club -> name }}</p>
                                @endforeach
                            </div>
                        </li>
                    </ul>
                    <ul class="panel-list">
                        <h4>Garantía y condiciones de envío</h4>
                        <hr>
                        <li class="row">
                            @if ($parent_product -> warranty == 1)
                                <div class="col-xs-12">
                                    <p><b>Garantia</b></p>
                                    <span class="label label-success">Posee garantía</span>
                                </div>
                        </li>
                        <li class="row">
                                <div class="col-sm-8">
                                    <p><b>Condiciones de garantía</b></p>
                                    <p>{{ $parent_product -> warranty_conditions }}</p>
                                </div>
                                <div class="col-sm-4">
                                    <p><b>Tiempo de garantía</b></p>
                                    <p>{{ $parent_product -> warranty_day }} días</p>
                                </div>
                            @endif
                        </li>
                        <li class="row">
                            <div class="col-xs-12">
                                <p><b>Condiciones de envío</b></p>
                                <p>{{ $parent_product -> delivery_conditions }}</p>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="col-md-6">
                    <div class="from-group">
                        <div class="text-center thumbnail mbl">
                            @if (empty($parent_image -> image))
                                <img  class="image-thumbnail max-size" src="{{ Storage::disk('images') -> url('img-default.png') }}" alt="{{ $parent_product-> name }}">
                            @else
                                <img  class="image-thumbnail max-size" src="{{ $_ENV['STORAGE_PATH'].$parent_image -> image }}" alt="{{ $parent_product -> name }}">
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @if (count($products)>0)
            <div class="panel filterable">
                <div class="panel-heading clearfix">
                    <h3 class="panel-title pull-left m-t-6"> Variantes</h3>
                    <a href="{{ url('admin/products/create/'. $parent_product -> id) }}" class="btn btn-success pull-right">Nuevo</a>
                </div>
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-hover" id="sample_1">
                            <thead>
                                <tr>
                                    <th>Característica</th>
                                    <th>SKU</th>
                                    <th>Código de barras</th>
                                    <th>Puntos</th>
                                    <th>Estatus</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($products as $datos)
                                    <tr>
                                        <td><a href="{{route('products.show', $datos -> id )}}">{{ $datos -> feature}}</a></td>
                                        <td>{{ $datos -> sku }}</td>
                                        <td>{{$datos -> barcode}}</td>
                                        <td>{{ number_format($datos -> points,0,',','.') }}</td>
                                        <td>@if ($datos -> status == 1) <span class="label label-success">Activo</span> @else <span class="label label-danger">Inactivo</span> @endif</td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        @endif
    </article>
@stop
@section('modals')
    <!-- MODAL PARA ELIMINAR REGISTRO -->
    <div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="modal-delete">
        <form action="{{ route('parents-products.destroy', $parent_product -> id) }}" method="POST">
            {{ csrf_field() }}
            <input type="hidden" name="_method" value="DELETE">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button id="modal-delete" type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Eliminar Producto</h4>
                    </div>
                    <div class="modal-body">
                        <p>¿Esta seguro de eliminar el producto <b>{{ $parent_product -> name}}</b>?</p>
                    </div>
                    <div class="modal-footer text-center">
                        <button type="button" class="btn btn-warning" data-dismiss="modal">Atrás</button>
                        <button type="submit" class="btn btn-danger">Eliminar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <!-- END MODAL PARA ELIMINAR REGISTRO -->
@endsection