routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::middleware('auth')->group(function(){
    // Rutas Web
	Route::get('/',                 			'WebController@index');
    Route::get('/directory',					'Web\DirectoryController@index')->name('directory');
    Route::post('/directory',					'Web\DirectoryController@search')->name('directory.search');
    Route::post('/directory/filter',		'Web\DirectoryController@filter')->name('directory.filter');
    Route::get('/ranking',						'Web\RankingController@index')->name('ranking');
    Route::get('/programs',						'Web\ProgramController@index');
    Route::get('/programs/{id}',				'Web\ProgramController@show');
    Route::get('/contact',						'WebController@contact');
    Route::get('/mall/product/{id}',          	'Web\StoreController@product') -> name('store.product');
    Route::get('/mall/market/{market}',         'Web\StoreController@market') -> name('store.market');
    Route::get('/mall/{category}',             	'Web\StoreController@category') -> name('store.category');
    Route::get('/mall/{category}/{subcategory}','Web\StoreController@subcategory') -> name('store.subcategory');
	Route::get('/mall',             			'Web\StoreController@index') -> name('store.index');
	Route::post('/mall',             			'Web\StoreController@filter') -> name('store.filter');
	Route::get('/shopping/branches/{branch_id}','WebController@branchCart');

	//Others routes
	Route::get('/politics', function() {
	    return view('web.others.politics');
	});
	Route::get('/terms', function() {
	    return view('web.others.terms');
	});
	Route::get('/faq', function() {
	    return view('web.others.faq');
	});

	//My account routes
	Route::get('/my-account/orders',      'Web\MyAccountController@orders')->name('my-account.orders');
    Route::get('/my-account/orders/{id}',      'Web\MyAccountController@order')->name('my-account.order');
    Route::post('/my-account/change-image/{id}',      'Web\MyAccountController@changeImage')->name('my-account.change-image');
    Route::get('/my-account/configuration',      'Web\MyAccountController@configuration')->name('my-account.configuration');
    Route::post('/my-account/change-password',      'Web\MyAccountController@changePassword')->name('my-account.change-password');
	Route::post('/my-account/edit-branch',      'Web\MyAccountController@updateBranch')->name('my-account.edit-branch');
    Route::get('/my-account',      'Web\MyAccountController@index')->name('my-account.index');
	Route::post('/my-account',      'Web\MyAccountController@update')->name('my-account.update');
	Route::post('/my-account/imessages/response/destroy',      'Web\MessageController@responseDestroy')->name('response.destroy');
	Route::post('/my-account/imessages/response/{id}',      'Web\MessageController@response')->name('imessage.response');
	Route::resource('/my-account/imessages',      'Web\MessageController');


    //Cart routes
    Route::get('/shopping',        	'Web\CartController@show')->name('cart.show');
    Route::post('/shopping/add-product/{id}',        	'Web\CartController@add')->name('cart.add');
    Route::get('/shopping/delete-product/{id}',        	'Web\CartController@delete')->name('cart.delete');
    Route::post('/shopping/update-products',        	'Web\CartController@update')->name('cart.update');
    Route::post('/shopping/destroy',        	'Web\CartController@destroy')->name('cart.destroy');
    Route::post('/shopping/order',        	'Web\CartController@generateOrder')->name('cart.order');

});


Route::prefix('admin')->group( function(){
	Route::post('/images/destroy', 						'Admin\AdminController@imageDestroy')->name('images.destroy');
	Route::post('/images/update', 						'Admin\AdminController@imageUpdate')->name('images.update');
	Route::get('/login',					'Admin\LoginController@showLoginForm')->name('admin.login');
	Route::post('/login',					'Admin\LoginController@login')->name('admin.login.submit');
	Route::post('/logout',					'Admin\LoginController@logout')->name('admin.logout');
	Route::post('password/email',					'Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	Route::get('password/reset',					'Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
	Route::post('password/reset',					'Admin\ResetPasswordController@reset');
	Route::get('password/reset/{token}',	'Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');

	Route::middleware('auth:user')->group(function(){

		Route::post('/profile/change-password', 'Admin\ProfileController@changePassword')->name('profile.change-password');
		Route::get('/lists/state/{id}', 		'Admin\ListController@getState');
		Route::get('/lists/city/{id}', 			'Admin\ListController@getCity');
		Route::post('guides/store/{id}',     	'Admin\GuideController@store')->name('guides.store');
		Route::get('/', 						'Admin\AdminController@index')->name('admin.dashboard');
		Route::get('/logs', 					'\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
		Route::get('/objetives/create/{id}',    'Admin\ObjetiveController@newcreate');
		Route::get('/products/create/{id}',     'Admin\ProductController@newCreate');
		Route::post('/members/import',          'Admin\MemberController@import')->name('members.import');
		Route::get('/members/filter',      		'Admin\MemberController@filter')->name('members.filter');
		Route::post('/departments/import',		'Admin\DepartmentController@import')->name('departments.import');
		Route::post('/branches/import',     	'Admin\BranchController@import')->name('branches.import');
		Route::get('/transactions/filter',      'Admin\TransactionController@filter')->name('transactions.filter');
		Route::post('/payload/insert-file',      	'Admin\PayloadController@InsertFile')->name('payload.insert_file');
        Route::get('/payload/filter',      		'Admin\PayloadController@filter')->name('payload.filter');
        Route::post('/groups/filter',      		'Admin\GroupController@filter')->name('groups.filter');
		Route::get('/orders/filter',      		'Admin\OrderController@filter')->name('orders.filter');
		Route::put('/orders/status/{id}',       'Admin\OrderController@status')->name('orders.status');
		Route::get('/orders/refund-create/{id}','Admin\OrderController@refund_create')->name('orders.refund-create');
		Route::post('/orders/refund-store/{id}','Admin\OrderController@refund_store')->name('orders.refund-store');
		Route::get('/accounts/filter/{id}',     'Admin\AccountController@filter')->name('accounts.filter');
		Route::get('/programs/filter',          'Admin\ProgramController@filter')->name('programs.filter');
		Route::get('/picking',          'Admin\PickingController@index');
		Route::get('/reports',          'Admin\ReportController@index');
		Route::get('/reports/inventory-output',          'Admin\ReportController@inventoryOutput');
		Route::get('/reports/exchange-item',          'Admin\ReportController@exchangeItem');
		Route::get('/reports/exchange-user',     'Admin\ReportController@exchangeUser');
		Route::get('/reports/exchange-item/filter',   'Admin\ReportController@exchangeFilter')->name('exchange-item.filter');
		Route::get('/reports/exchange-user/filter',   'Admin\ReportController@exchangeUserFilter')->name('exchange-user.filter');
		Route::get('/reports/contribution-exchange',   'Admin\ReportController@reportContributionAndExchange');
		Route::get('/reports/contribution-exchange/filter',   'Admin\ReportController@reportContributionAndExchangeFilter')->name('contribution-exchange.filter');
		Route::get('/reports/inventory-output/filter',          'Admin\ReportController@inventoryOutputFilter')->name('reports.inventory-output.filter');
		Route::resource('/consolidated',        'Admin\AccountController');
		Route::resource('/transactions',        'Admin\TransactionController');
		Route::resource('/payload',             'Admin\PayloadController');
		Route::resource('/accounts',            'Admin\AccountController');
		Route::post('/profile/image-change/{id}',		'Admin\ProfileController@imageChange');
		Route::resource('/profile',				'Admin\ProfileController');
		Route::resource('/users', 				'Admin\UserController');
		Route::resource('/roles', 				'Admin\RoleController');
		Route::resource('/clubs', 				'Admin\ClubController');
		Route::resource('/brands', 		  		'Admin\BrandController');
		Route::resource('/categories', 			'Admin\CategoryController');
		Route::resource('/subcategories', 		'Admin\SubcategoryController');
		Route::resource('/offers', 				'Admin\OfferController');
		Route::resource('/affiliates', 			'Admin\AffiliateController');
		Route::resource('/parents-products', 	'Admin\ParentProductController');
		Route::resource('/inventory', 			'Admin\InventoryController');
		Route::resource('/products', 			'Admin\ProductController');
		Route::resource('/agents', 				'Admin\AgentController');
		Route::resource('/orders', 				'Admin\OrderController');
		Route::resource('/programs', 			'Admin\ProgramController');
		Route::resource('/groups', 				'Admin\GroupController');
		Route::resource('/objetives', 			'Admin\ObjetiveController');
		Route::resource('/members', 			'Admin\MemberController');
		Route::resource('/branches',     		'Admin\BranchController');
		Route::resource('departments',     		'Admin\DepartmentController');
		Route::post('/messages/change-status',      'Admin\MessageController@updateStatus')->name('message.change-status');
		Route::post('/messages/response/destroy',      'Admin\MessageController@responseDestroy')->name('responses.destroy');
		Route::post('/messages/response/{id}',      'Admin\MessageController@response')->name('message.response');

app/Models/Program.php
<?php

namespace Meritop\Models;

use Illuminate\Database\Eloquent\Model;

class Program extends Model
{
  protected $table = 'programs';

  protected $fillable = [
      'id', 'name', 'description', 'status', 'fk_id_club', 'deleted'
  ];

  public function objetive()
  {
    return $this->hasmany(Objetive::class);
  }
}

app/Http/Controllers/Web/ProgramController.php
<?php

namespace Meritop\Http\Controllers\Web;

use Illuminate\Http\Request;
use Meritop\Http\Controllers\Controller;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Meritop\Models\Program;
use Meritop\Models\Objetive;
use Meritop\Models\Quote;

class ProgramController extends Controller
{
    public function index()
    {
        $programs = Program::select('programs.*', 'media.image', 'media.slug')
        ->join('objetives', 'objetives.fk_id_program', 'programs.id')
        ->join('media', 'media.identificator', 'programs.id')
        ->join('groups_programs', 'groups_programs.fk_id_program', 'programs.id')
        ->join('members_groups', 'members_groups.fk_id_group', 'groups_programs.fk_id_group')
        ->where([
            'programs.status' => true,
            'objetives.status' => true,
            'fk_id_club' => session('club')->id,
            'table' => 'programs',
            'members_groups.fk_id_member' => Auth::user()->id,
        ])
        ->whereDate('objetives.due_date', '>=', date('Y-m-d'))
        ->distinct()
        ->get();

        $quotes = Quote::all();

        return view('web.programs')->with(['programs' => $programs, 'quotes' => $quotes]);
    }

    public function show($id)
    {
        $program = Program::select('programs.*', 'media.image', 'media.slug')
        ->join('objetives', 'objetives.fk_id_program', 'programs.id')
        ->join('media', 'media.identificator', 'programs.id')
        ->where([
            'programs.id' => $id,
            'media.table' => 'programs',
            'programs.status' => true,
            'objetives.status' => true,
        ])
        ->whereDate('objetives.due_date', '>=', date('Y-m-d'))
        ->first();

        if (empty($program)) {
            return redirect('/programs');
        }

        $objetives = Objetive::select('objetives.*', 'perspectives.name as perspective')
        ->join('perspectives', 'perspectives.id', 'objetives.fk_id_perspective')
        ->where([
            'objetives.fk_id_program' => $id,
            'objetives.status' => true,
        ])
        ->whereDate('objetives.due_date', '>=', date('Y-m-d'))
        ->get();

        return view('web.program')->with(['program' => $program, 'objetives' => $objetives]);
    }

}

resources/views/admin/programs/edit.blade.php
@extends('layouts.admin.default')

@section('title', 'Programa')
@section('styles')
    <link rel="stylesheet" type="text/css" href="{{asset('core-plus-theme/css/custom_css/dashboard1.css')}}" />

    <!--Datepicker css -->
    <link rel="stylesheet" href="{{ asset('core-plus-theme/vendors/datetime/css/jquery.datetimepicker.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('core-plus-theme/vendors/airdatepicker/css/datepicker.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('core-plus-theme/css/datepicker.css') }}">
    <!-- end Datepicker css -->

    <link rel="stylesheet" type="text/css" href="{{ asset('core-plus-theme/vendors/bootstrap3-wysihtml5-bower/css/bootstrap3-wysihtml5.min.css')}}" />
    <link rel="stylesheet" media="screen" type="text/css" href="{{ asset('core-plus-theme/vendors/summernote/summernote.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('core-plus-theme/vendors/trumbowyg/css/trumbowyg.min.css') }}" >
     <link rel="stylesheet" type="text/css" href="{{ asset ('core-plus-theme/css/custom.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('core-plus-theme/css/form_editors.css') }}">
@stop
@section('content')
    <!-- Content Header (Page header) -->
     <header class="header-page">
        <div class="header-data">
            <h1>@yield('title') <small>- Editar</small></h1>
        </div>
    </header>
	<article class="content">
        <form id="form-validation" action="{{ route('programs.update', $program -> id) }}" method="POST">
            {{ csrf_field() }}
            @include('layouts.form-errors')
            <input name="_method" type="hidden" value="PUT">
			<div class="panel">
                <div class="panel-heading clearfix">
                    <div class="pull-right text-center">
                        <a href="{{route('programs.show',$program -> id )}}" type="button" class="btn btn-warning">Atrás</a>
                        <button type="submit" class="btn btn-success">Aceptar</button>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="form-group">
                        <label for="name" class="control-label">Nombre <span class="text-danger">*</span></label>
                        <input id="name" name="name" placeholder="Nombre del programa" maxlength="100" type="text" class="form-control" required="required" value="{{ $program -> name }}" />
                    </div>
                     <div class="form-group">
                        <label for="summernote" class="control-label">Descripción<span class="text-danger">*</span></label>
                        <div class="panel-body ">
                            <div class="bootstrap-admin-panel-content summer_noted">
                                <textarea id="summernote" name="description" placeholder="Descripcion" maxlength="65500" class="form-control" required="required" rows="15">{{ $program -> description }}</textarea>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label">Grupo <span class="text-danger">*</span></label>
                        <div class="col-xs-12">
                            @if (count($groups)>0)
                                @foreach ($groups as $element)
                                    <div class="checkbox checkbox-primary col-md-3" >
                                        <input id="check{{ $element -> id }}" name="fk_id_group[]" value="{{ $element -> id }}" class="styled" type="checkbox"
                                        @foreach ($groups_programs as $data)
                                            @if ($element -> id == $data -> fk_id_group) checked="checked" @endif
                                        @endforeach
                                        >
                                        <label for="check{{ $element -> id }}" name="fk_id_group[]" value="{{ $element -> id }}"  @if ($program -> group == $element -> id) selected="selected" @endif>
                                            &nbsp;{{ $element -> name }}
                                        </label>
                                    </div>
                                @endforeach
                            @else
                                <p>No hay grupos registrados. Si desea registrar un grupo dirigase a <a href="{{ route('groups.create') }}">Crear un grupo</a></p>
                            @endif
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="status" class="control-label">Estatus <span class="text-danger">*</span></label>
                        <select name="status" id="status" class="form-control" required="required">
                            <option value="">Seleccione...</option>
                            <option value="1" @if ($program -> status == 1) selected="selected" @endif>Activo</option>
                            <option value="0" @if ($program -> status == 0) selected="selected" @endif>Inactivo</option>
                        </select>
                    </div>
                </div>
            </div>
        </form>
	</article>
@stop
@section('scripts')
      <!-- form editores -->
    <script type="text/javascript" src="{{ asset('core-plus-theme/vendors/bootstrap3-wysihtml5-bower/js/bootstrap3-wysihtml5.all.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('core-plus-theme/vendors/trumbowyg/js/trumbowyg.js') }}" ></script>
    <script type="text/javascript" src="{{ asset('core-plus-theme/vendors/bootstrap3-wysihtml5-bower/js/bootstrap3-wysihtml5.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('core-plus-theme/vendors/summernote/summernote.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('core-plus-theme/js/custom_js/form_editors.js') }}" ></script>
    <!-- end form editores -->

    <!-- Page js -->
    <script type="text/javascript" src="{{asset('vendors/datatables/js/jquery.dataTables.js')}}"></script>
    <script type="text/javascript" src="{{asset('vendors/datatables/js/dataTables.bootstrap.js')}}"></script>
    <script type="text/javascript" src="{{asset('js/custom_js/datatables_custom.js')}}"></script>
    <!-- end page js -->
    <!-- bootstrap validation -->
    <script type="text/javascript" src="{{asset('core-plus-theme/vendors/bootstrapvalidator/js/bootstrapValidator.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('core-plus-theme/vendors/bootstrap-maxlength/js/bootstrap-maxlength.js')}}"></script>
    <script type="text/javascript" src="{{asset('core-plus-theme/customs/form-validator.js')}}"></script>
    <!-- end bootstrap validation -->
@endsection

resources/views/admin/programs/show.blade.php
@extends('layouts.admin.default')

@section('title', 'Programa')
@section('styles')
    <link rel="stylesheet" type="text/css" href="{{asset('core-plus-theme/css/custom_css/dashboard1.css')}}" />
    <link rel="stylesheet" type="text/css" href="{{ asset('core-plus-theme/vendors/datatables/css/dataTables.bootstrap.css') }}"/>
@stop
@section('content')
    <!-- Content Header (Page header) -->
     <header class="header-page">
         <div class="header-data">
            <h1>@yield('title')<small> - Ver</small></h1>
        </div>
    </header>
    @include('flash::message')
    <article class="content">
            <div class="panel">
                <div class="panel-heading clearfix">
                    <div class="pull-right">
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal-delete">Eliminar</button>
                        <a href="{{ route('programs.index') }}" type="button" class="btn btn-warning">Atrás</a>
                        <a href="{{ route('programs.edit', $program -> id) }}" type="button" class="btn btn-primary">Editar</a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="col-sm-12 col-md-6">
                         <ul class="panel-list">
                            <li class="row">
                                <p><b>Nombre</b></p>
                                <p class="text-capitalize">{{ $program -> name }}</p>
                            </li>
                            <li class="row">
                                <br>    
                                <p><b>Grupos</b></p>
                                @foreach ($groups_programs as $element)
                                    <span class="label label-primary">{{ $element -> name }}</span>
                                @endforeach
                            </li>   
                             <li class="row">
                                <p><b>Estatus</b></p>
                                <p>@if ($program -> status == 1) <span class="label label-success">Activo</span> @else <span class="label label-danger">Inactivo</span> @endif</p>
                            </li>
                        </ul>
                    </div>
                    <div class="col-sm-12 col-md-6">
                        <div class="form-group">
                             <div class="text-center thumbnail mbl">
                                @if (empty($program -> image))
                                    <img  class="image-thumbnail img-responsive max-size" src="{{ Storage::disk('images') -> url('img-default.png') }}" alt="{{ $program -> name }}">
                                @else
                                    <img  class="image-thumbnail img-responsive max-size" src="{{ $_ENV['STORAGE_PATH'].$program -> image }}" alt="{{ $program -> name }}">
                                @endif
                            </div>
                        </div>
                    </div>
                    <ul class="panel-list">
                        <li class="row">
                            <div class="col-sm-12">
                                <p><b>Descripción</b></p>
                                <p>{!! $program -> description !!}</p>
                            </div>
                        </li> 
                        <li class="row">
                            <div class="col-sm-6 col-md-12 col-lg-6">
                                <p><b>Creación</b></p>
                                <p class="text-capitalize">{{ date_format($program -> created_at, 'd/m/Y') }}</p>
                            </div>
                            <div class="col-sm-6 col-md-12 col-lg-6">
                                <p><b>Modificación</b></p>
                                <p class="text-capitalize">{{ date_format($program -> updated_at, 'd/m/Y') }}</p>
                            </div>
                        </li>  
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <div class="panel filterable">
                        <div class="panel-heading clearfix">
                          {{--   <div class="btns-header pull-left">
                                <button  data-toggle="collapse" data-parent="#accordion-cat-1" href="#faq-cat-1-sub-1" type="button" class="btn btn-labeled btn-meritop-primary">
                                    <span class="btn-label"><i class="glyphicon glyphicon-chevron-down"></i></span> Filtros
                                </button>
                            </div> --}}
                            <div class="panel-faq">
                               {{--  <form method="post" action=" {{ route('objetives.filter') }} ">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="get">
                                    <div id="faq-cat-1-sub-1" class="collapse">
                                        <div class="panel-body">
                                            <div class="form-inline" style="display: block; overflow: hidden;">
                                                <div class="form-group pull-left">
                                                    <label class="control-label" for="dateranges">Rango de fecha: </label>
                                                    <input name="date" type="text" data-range="true" data-multiple-dates-separator=" - " data-language="en" class="form-control" id="dateranges" readonly="readonly" value="{{ date('01/m/Y') }} - {{ date('d/m/Y') }}"/>
                                                </div>
                                                <div class="form-group pull-left">
                                                    <button type="submit" class="btn btn-meritop-primary btn-md" id="addButton">Buscar</button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </form> --}}

                            {{-- <form action="{{ route('objetives.create') }}" method="post">
                                {{ csrf_field() }}
                                <input type="hidden" name="_method" value="get">
                                <input type="hidden" name="id" value="{{ $program -> id }}">
                                <input type="submit" class="btn btn-primary pull-right" value="Agregar Variante">
                            </form> --}}
                            <div class="pull-right">
                                <a href="{{ url('admin/objetives/create/'. $program -> id) }}" class="btn btn-success" id="addButton">Nuevo</a>
                            </div>
                        </div>
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-hover" id="sample_1">
                                    <thead>
                                        <tr>
                                            <th>Código</th>
                                            <th>Nombre</th>
                                            <th>Perspectiva</th>
                                            <th>Fecha inicio</th>
                                            <th>Fecha fin</th>
                                            <th>Estatus</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (count($objetives) > 0)
                                            @foreach($objetives as $element)
                                                <tr>
                                                    <td><a href="{{route('objetives.show', $element -> id)}}">{{ $element -> code }}</a></td>
                                                    <td class="text-capitalize">{{ $element -> name }}</td>
                                                    <td class="text-capitalize">{{ $element -> perspective }}</td>
                                                    <td>{{ date_format( new DateTime($element -> start_date), 'd/m/Y') }}</td>
                                                    <td>{{ date_format(new DateTime($element -> due_date), 'd/m/Y') }}</td>
                                                    <td>@if ($element -> status == 1) <span class="label label-success">Activo</span> @else <span class="label label-danger">Inactivo</span> @endif</td>
                                                </tr>
                                            @endforeach
                                        @else
                                            <tr>
                                                <td colspan="9"><p class="text-center">No hay objetivos registrados para este programa</p></td>
                                            </tr>
                                        @endif
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </article>
@stop
@section('modals')
    <!-- Modal -->
    <div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="modal-delete">
        <form action="{{ route('programs.destroy', $program -> id) }}" method="POST">
            {{ csrf_field() }}
            <input type="hidden" name="_method" value="DELETE">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Eliminar programa</h4>
                    </div>
                    <div class="modal-body">
                        <p>¿Esta seguro de eliminar el programa <b>{{ $program -> name }}</b>?</p>
                    </div>
                    <div class="modal-footer text-center">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-danger">Eliminar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
    <!-- end modal -->
@stop
@section('scripts')
    <!-- page js -->
    <script type="text/javascript" src="{{ asset('core-plus-theme/vendors/datatables/js/jquery.dataTables.js') }}"></script>
    <script type="text/javascript" src="{{ asset('core-plus-theme/vendors/datatables/js/dataTables.bootstrap.js') }}"></script>
    <script type="text/javascript" src="{{ asset('core-plus-theme/js/custom_js/datatables_custom.js') }}"></script>
    <!-- end page js -->
    <!-- DateRange Picked js -->
    <script type="text/javascript" src="{{ asset('core-plus-theme/vendors/datetime/js/jquery.datetimepicker.full.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('core-plus-theme/vendors/airdatepicker/js/datepicker.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('core-plus-theme/vendors/airdatepicker/js/datepicker.en.js') }}"></script>
    <script type="text/javascript" src="{{ asset('core-plus-theme/js/custom_js/advanceddate_pickers.js') }}"></script>

@endsection