routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::middleware('auth')->group(function(){
    // Rutas Web
	Route::get('/',                 			'WebController@index');
    Route::get('/directory',					'Web\DirectoryController@index')->name('directory');
    Route::post('/directory',					'Web\DirectoryController@search')->name('directory.search');
    Route::post('/directory/filter',		'Web\DirectoryController@filter')->name('directory.filter');
    Route::get('/ranking',						'Web\RankingController@index')->name('ranking');
    Route::get('/programs',						'Web\ProgramController@index');
    Route::get('/programs/{id}',				'Web\ProgramController@show');
    Route::get('/contact',						'WebController@contact');
    Route::get('/mall/product/{id}',          	'Web\StoreController@product') -> name('store.product');
    Route::get('/mall/market/{market}',         'Web\StoreController@market') -> name('store.market');
    Route::get('/mall/{category}',             	'Web\StoreController@category') -> name('store.category');
    Route::get('/mall/{category}/{subcategory}','Web\StoreController@subcategory') -> name('store.subcategory');
	Route::get('/mall',             			'Web\StoreController@index') -> name('store.index');
	Route::post('/mall',             			'Web\StoreController@filter') -> name('store.filter');
	Route::get('/shopping/branches/{branch_id}','WebController@branchCart');

	//Others routes
	Route::get('/politics', function() {
	    return view('web.others.politics');
	});
	Route::get('/terms', function() {
	    return view('web.others.terms');
	});
	Route::get('/faq', function() {
	    return view('web.others.faq');
	});

	//My account routes
	Route::get('/my-account/orders',      'Web\MyAccountController@orders')->name('my-account.orders');
    Route::get('/my-account/orders/{id}',      'Web\MyAccountController@order')->name('my-account.order');
    Route::post('/my-account/change-image/{id}',      'Web\MyAccountController@changeImage')->name('my-account.change-image');
    Route::get('/my-account/configuration',      'Web\MyAccountController@configuration')->name('my-account.configuration');
    Route::post('/my-account/change-password',      'Web\MyAccountController@changePassword')->name('my-account.change-password');
	Route::post('/my-account/edit-branch',      'Web\MyAccountController@updateBranch')->name('my-account.edit-branch');
    Route::get('/my-account',      'Web\MyAccountController@index')->name('my-account.index');
	Route::post('/my-account',      'Web\MyAccountController@update')->name('my-account.update');
	Route::post('/my-account/imessages/response/destroy',      'Web\MessageController@responseDestroy')->name('response.destroy');
	Route::post('/my-account/imessages/response/{id}',      'Web\MessageController@response')->name('imessage.response');
	Route::resource('/my-account/imessages',      'Web\MessageController');


    //Cart routes
    Route::get('/shopping',        	'Web\CartController@show')->name('cart.show');
    Route::post('/shopping/add-product/{id}',        	'Web\CartController@add')->name('cart.add');
    Route::get('/shopping/delete-product/{id}',        	'Web\CartController@delete')->name('cart.delete');
    Route::post('/shopping/update-products',        	'Web\CartController@update')->name('cart.update');
    Route::post('/shopping/destroy',        	'Web\CartController@destroy')->name('cart.destroy');
    Route::post('/shopping/order',        	'Web\CartController@generateOrder')->name('cart.order');

});


Route::prefix('admin')->group( function(){
	Route::post('/images/destroy', 						'Admin\AdminController@imageDestroy')->name('images.destroy');
	Route::post('/images/update', 						'Admin\AdminController@imageUpdate')->name('images.update');
	Route::get('/login',					'Admin\LoginController@showLoginForm')->name('admin.login');
	Route::post('/login',					'Admin\LoginController@login')->name('admin.login.submit');
	Route::post('/logout',					'Admin\LoginController@logout')->name('admin.logout');
	Route::post('password/email',					'Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	Route::get('password/reset',					'Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
	Route::post('password/reset',					'Admin\ResetPasswordController@reset');
	Route::get('password/reset/{token}',	'Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');

	Route::middleware('auth:user')->group(function(){

		Route::post('/profile/change-password', 'Admin\ProfileController@changePassword')->name('profile.change-password');
		Route::get('/lists/state/{id}', 		'Admin\ListController@getState');
		Route::get('/lists/city/{id}', 			'Admin\ListController@getCity');
		Route::post('guides/store/{id}',     	'Admin\GuideController@store')->name('guides.store');
		Route::get('/', 						'Admin\AdminController@index')->name('admin.dashboard');
		Route::get('/logs', 					'\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
		Route::get('/objetives/create/{id}',    'Admin\ObjetiveController@newcreate');
		Route::get('/products/create/{id}',     'Admin\ProductController@newCreate');
		Route::post('/members/import',          'Admin\MemberController@import')->name('members.import');
		Route::get('/members/filter',      		'Admin\MemberController@filter')->name('members.filter');
		Route::post('/departments/import',		'Admin\DepartmentController@import')->name('departments.import');
		Route::post('/branches/import',     	'Admin\BranchController@import')->name('branches.import');
		Route::get('/transactions/filter',      'Admin\TransactionController@filter')->name('transactions.filter');
		Route::post('/payload/insert-file',      	'Admin\PayloadController@InsertFile')->name('payload.insert_file');
        Route::get('/payload/filter',      		'Admin\PayloadController@filter')->name('payload.filter');
        Route::post('/groups/filter',      		'Admin\GroupController@filter')->name('groups.filter');
		Route::get('/orders/filter',      		'Admin\OrderController@filter')->name('orders.filter');
		Route::put('/orders/status/{id}',       'Admin\OrderController@status')->name('orders.status');
		Route::get('/orders/refund-create/{id}','Admin\OrderController@refund_create')->name('orders.refund-create');
		Route::post('/orders/refund-store/{id}','Admin\OrderController@refund_store')->name('orders.refund-store');
		Route::get('/accounts/filter/{id}',     'Admin\AccountController@filter')->name('accounts.filter');
		Route::get('/programs/filter',          'Admin\ProgramController@filter')->name('programs.filter');
		Route::get('/picking',          'Admin\PickingController@index');
		Route::get('/reports',          'Admin\ReportController@index');
		Route::get('/reports/inventory-output',          'Admin\ReportController@inventoryOutput');
		Route::get('/reports/exchange-item',          'Admin\ReportController@exchangeItem');
		Route::get('/reports/exchange-user',     'Admin\ReportController@exchangeUser');
		Route::get('/reports/exchange-item/filter',   'Admin\ReportController@exchangeFilter')->name('exchange-item.filter');
		Route::get('/reports/exchange-user/filter',   'Admin\ReportController@exchangeUserFilter')->name('exchange-user.filter');
		Route::get('/reports/contribution-exchange',   'Admin\ReportController@reportContributionAndExchange');
		Route::get('/reports/contribution-exchange/filter',   'Admin\ReportController@reportContributionAndExchangeFilter')->name('contribution-exchange.filter');
		Route::get('/reports/inventory-output/filter',          'Admin\ReportController@inventoryOutputFilter')->name('reports.inventory-output.filter');
		Route::resource('/consolidated',        'Admin\AccountController');
		Route::resource('/transactions',        'Admin\TransactionController');
		Route::resource('/payload',             'Admin\PayloadController');
		Route::resource('/accounts',            'Admin\AccountController');
		Route::post('/profile/image-change/{id}',		'Admin\ProfileController@imageChange');
		Route::resource('/profile',				'Admin\ProfileController');
		Route::resource('/users', 				'Admin\UserController');
		Route::resource('/roles', 				'Admin\RoleController');
		Route::resource('/clubs', 				'Admin\ClubController');
		Route::resource('/brands', 		  		'Admin\BrandController');
		Route::resource('/categories', 			'Admin\CategoryController');
		Route::resource('/subcategories', 		'Admin\SubcategoryController');
		Route::resource('/offers', 				'Admin\OfferController');
		Route::resource('/affiliates', 			'Admin\AffiliateController');
		Route::resource('/parents-products', 	'Admin\ParentProductController');
		Route::resource('/inventory', 			'Admin\InventoryController');
		Route::resource('/products', 			'Admin\ProductController');
		Route::resource('/agents', 				'Admin\AgentController');
		Route::resource('/orders', 				'Admin\OrderController');
		Route::resource('/programs', 			'Admin\ProgramController');
		Route::resource('/groups', 				'Admin\GroupController');
		Route::resource('/objetives', 			'Admin\ObjetiveController');
		Route::resource('/members', 			'Admin\MemberController');
		Route::resource('/branches',     		'Admin\BranchController');
		Route::resource('departments',     		'Admin\DepartmentController');
		Route::post('/messages/change-status',      'Admin\MessageController@updateStatus')->name('message.change-status');
		Route::post('/messages/response/destroy',      'Admin\MessageController@responseDestroy')->name('responses.destroy');
		Route::post('/messages/response/{id}',      'Admin\MessageController@response')->name('message.response');

app/Models/Subcategory.php
<?php

namespace Meritop\Models;

use Illuminate\Database\Eloquent\Model;

class Subcategory extends Model
{
    protected $table = 'subcategories';

    protected $fillable = [
        'id', 'name', 'description', 'slug', 'status', 'fk_id_category',
    ];

    public function  productSubcategory()
    {
      return $this->hasmany(ProductSubcategory::class);
    }

}

app/Http/Controllers/Admin/SubcategoryController.php
<?php

namespace Meritop\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Meritop\Http\Controllers\Controller;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Meritop\Models\Subcategory;
use Meritop\Models\Category;
use Meritop\Http\Assets\ResourceFunctions;
use Meritop\Http\Requests\Admin\Subcategory\SubcategoryCreateRequest;
use Meritop\Http\Requests\Admin\Subcategory\SubcategoryUpdateRequest;

class SubcategoryController extends Controller
{
    public $module = 11;
    /**
     * Display a listing of the subcategory.
     *
     *  @return the view(index)
     */

    public function index()
    {
        /*
        *Method that allows the validation of privileges
        */
        if ((ResourceFunctions::validationReturn($this->module,1)) !=true) {
            return redirect()->route('admin.dashboard');
        }

        Log::info('Ingreso exitoso a SubcategoryController - index(), del usuario: '.Auth::guard('user')->user()->user_name);

        $subcategories = Subcategory::all();
        $num_subcategories = $subcategories -> count();

        return view('admin/subcategories/index')->with(['subcategories' => $subcategories, 'num_subcategories' => $num_subcategories]);
    }

    /**
     * Show the form for creating a new subcategory.
     *
     * @return the view(create)
     */
    public function create()
    {
        /*
        *Method that allows the validation of privileges
        */
        if ((ResourceFunctions::validationReturn($this->module,3)) !=true) {
            return redirect()->route('admin.subcategories.index');
        }

        Log::info('Ingreso exitoso a SubcategoryController - create(), del usuario: '.Auth::guard('user')->user()->user_name);

        $categories = Category::all();

        return view('admin/subcategories/create')->with(['categories' => $categories]);
    }

    /**
     * Store a newly created subcategory in storage.
     *
     * @param  \Illuminate\Http\Request - $request (all parameters from the view)
     * @return redirect view(index)
     */
    public function store(SubcategoryCreateRequest $request)
    {
        /*
        *Method that allows the validation of privileges
        */
        if ((ResourceFunctions::validationReturn($this->module,3)) !=true) {
            return redirect()->route('admin.dashboard');
        }

        try {
            DB::beginTransaction();

            Subcategory::create($request->all());

            ResourceFunctions::createHistoricalAction('crear','Ha realizado el registro: '.$request->name);

            DB::commit();

            ResourceFunctions::messageSuccess('SubcategoryController','store');

        } catch (\Exception $e) {
            DB::rollBack();
            ResourceFunctions::messageError('SubcategoryController','store',$e);
        }

        return redirect()->route('subcategories.index');
    }

    /**
     * Display the specified subcategory.
     *
     * @param  int  $id - (id of the particular subcategory)
     * @return the view(show)
     */
    public function show($id)
    {
        /*
        *Method that allows the validation of privileges
        */
        if ((ResourceFunctions::validationReturn($this->module,2)) !=true) {
            return redirect()->route('admin.dashboard');
        }

        Log::info('Ingreso exitoso a SubcategoryController - show(), del usuario: '.Auth::guard('user')->user()->user_name);

        $subcategory = Subcategory::select('subcategories.*', 'categories.name as category')
        ->join('categories', 'categories.id', '=', 'subcategories.fk_id_category')
        ->where('subcategories.id', $id)
        ->get();

        return view('admin/subcategories/show')->with(['subcategory' => $subcategory]);
    }

    /**
     * Show the form for editing the specified subcategory.
     *
     * @param  int  $id (id of the particular subcategory)
     * @return the view(edit)
     */
    public function edit($id)
    {
        /*
        *Method that allows the validation of privileges
        */
        if ((ResourceFunctions::validationReturn($this->module,4)) !=true) {
            return back();
        }

        Log::info('Ingreso exitoso a SubcategoryController - edit(), del usuario: '.Auth::guard('user')->user()->user_name);

        $subcategory = Subcategory::FindOrFail($id);
        $categories = Category::all();

        return view('admin/subcategories/edit')->with(['subcategory' => $subcategory, 'categories' => $categories]);
    }

    /**
     * Update the specified subcategory in storage.
     *
     * @param  \Illuminate\Http\Request - $request (all parameters from the view)
     * @param  int  $id (id of the particular subcategory)
     * @return redirect view(index)
     */
    public function update(SubcategoryUpdateRequest $request, $id)
    {
        /*
        *Method that allows the validation of privileges
        */
        if ((ResourceFunctions::validationReturn($this->module,4)) !=true) {
            return redirect()->route('admin.dashboard');
        }

        try {
            DB::beginTransaction();

            Subcategory::where('id', $id)
            ->update([
                    'name' => $request->name,
                    'description' => $request->description,
                    'slug' => $request->slug,
                    'status' => $request->status,
                    'fk_id_category' => $request->fk_id_category
                    ]);

            ResourceFunctions::createHistoricalAction('actualizar','Se ha realizado una actualización sobre el registro: '.$request->name);

            DB::commit();

            ResourceFunctions::messageSuccess('SubcategoryController','actualizar');

        } catch (\Exception $e) {
            DB::rollBack();
            ResourceFunctions::messageError('SubcategoryController','actualizar',$e);
        }

        return redirect()->route('subcategories.index');
    }

    /**
     * Remove the specified subcategory from storage.
     *
     * @param  int  $id (id of the particular subcategory)
     * @return redirect view(index)
     */
    public function destroy($id)
    {
        /*
        *Method that allows the validation of privileges
        */
        if ((ResourceFunctions::validationReturn($this->module,5)) !=true) {
            return back();
        }

        try {
            DB::beginTransaction();

            Subcategory::destroy($id);

            ResourceFunctions::createHistoricalAction('eliminar','Se ha eliminado el registro: '.$id);

            DB::commit();

            ResourceFunctions::messageSuccess('SubcategoryController','eliminar');

        } catch (\Exception $e) {
            DB::rollBack();
            ResourceFunctions::messageError('SubcategoryController','eliminar',$e);
        }

        return redirect()->route('subcategories.index');
    }
}

resources/views/admin/subcategories/edit.blade.php
@extends('layouts.admin.default')

@section('title', 'Subcategoría')
@section('styles')
    <link rel="stylesheet" type="text/css" href="{{asset('core-plus-theme/css/custom_css/dashboard1.css')}}" />
@stop
@section('content')
    <!-- Content Header (Page header) -->
    <header class="header-page">
        <div class="header-data">
            <h1>@yield('title') <small> - Editar</small></h1>
        </div>
    </header>
	<article class="content">
        <form id="form-validation" action="{{ route('subcategories.update',$subcategory -> id) }}" method="POST">
            {{ csrf_field() }}
            @include('layouts.form-errors')
            <input name="_method" type="hidden" value="PUT">
    			<div class="panel">
                    <div class="panel-heading clearfix">
                        <div class="pull-right text-center">
                            <a href="{{route('subcategories.show', $subcategory -> id) }}" type="button" class="btn btn-warning">Atrás</a>
                            <button type="submit" class="btn btn-success">Aceptar</button>
                        </div>
                    </div>
                    <div class="panel-body row">
                        <div class="col-sm-12 col-md-7">
                            <div class="form-group">
                                <label for="name" class="control-label">Nombre <span class="text-danger">*</span></label>
                                <input name="name" type="text" class="form-control  text-capitalize" id="name" placeholder="Nombre" value="{{$subcategory -> name}}" required="required">
                            </div>
                            <div class="form-group">
                                <label for="description" class="control-label">Descripción <span class="text-danger">*</span></label>
                                <textarea name="description" class="form-control" id="description" placeholder="Descripcion"" required="required" rows="10">{{ $subcategory -> description }}</textarea>
                            </div>
                            <div class="form-group">
                                <label for="slug" class="control-label">Slug <span class="text-danger">*</span></label>
                                <input name="slug" type="text" class="form-control" id="slug" placeholder="Slug" value="{{$subcategory -> slug}}" required="required">
                            </div>
                        </div>
                        <div class="col-sm-12 col-md-5">
                        <div class="form-group">
                            <label for="category" class="control-label">Categoria <span class="text-danger">*</span></label>
                            @if (count($categories)>0)
                                <select id="category" name="fk_id_category" class="form-control text-capitalize" data-bv-field="status" required="required">
                                    <option value="">Seleccione una categoria...</option>
                                    @foreach ($categories as $value)
                                        <option value="{{ $value->id }}" @if ($value->id == $subcategory->fk_id_category) selected="selected" @endif>{{ $value->name }}</option>
                                    @endforeach
                                </select>
                            @else
                                <p class="text-danger">No hay categorias registradas.</p>
                                <p>Si desea registrar una categoria haga click <a href="{{ route(categories.index) }}" title="Categorias">aquí</a>.</p>
                            @endif
                        </div>
                        <div class="form-group">
                            <label for="estatus" class="control-label">Estatus <span class="text-danger">*</span></label>
                            <select id="status" name="status" class="form-control" data-bv-field="status" required="required">
                                <option value="">Seleccione un estatus...</option>
                                <option value="1" @if($subcategory -> status == 1 ) selected="selected" @endif>Activo</option>
                                <option value="0" @if($subcategory -> status == 0 ) selected="selected" @endif>Inactivo</option>
                            </select>
                        </div>
                    </div>
                </div>
            <div>
        </form>
	</article>
@endsection

resources/views/admin/subcategories/index.blade.php
@extends('layouts.admin.default')

@section('title', 'Subcategorías')
@section('styles')
    <link rel="stylesheet" type="text/css" href="{{asset('core-plus-theme/css/custom_css/dashboard1.css')}}" />
    <link rel="stylesheet" type="text/css" href="{{ asset('core-plus-theme/vendors/datatables/css/dataTables.bootstrap.css') }}"/>
@stop
@section('content')
    <!-- Content Header (Page header) -->
    <header class="header-page">
        <div class="header-data">
            <h1>@yield('title') <small> - Gestiones</small></h1>
        </div>
    </header>
    @include('flash::message')
	<article class="content">
		<div class="panel filterable">
            <div class="panel-heading clearfix">
                <h3 class="panel-title pull-left m-t-6">
                </h3>
                <div class="pull-right">
                    <a href="{{ route('subcategories.create')}}" class="btn btn-success btn-md" id="addButton">Nuevo</a>
                </div>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-hover datatable-asc">
                        <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Descripción</th>
                            <th>Slug</th>
                            <th>Estatus</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($subcategories as $datos)
                        <tr>
                            <td class="text-capitalize"><a href="{{route('subcategories.show',$datos -> id)}}">{{$datos -> name}}</a></td>
                            <td>{{$datos -> description}}</td>
                            <td>{{$datos -> slug}}</td>
                            <td>@if ( $datos -> status == 1) <span class="label label-success">Activo</span> @else <span class="label label-danger">Inactivo</span> @endif</td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
	</article>
@stop
@section('scripts')
    <!-- page js -->
    <script type="text/javascript" src="{{asset('core-plus-theme/vendors/datatables/js/jquery.dataTables.js')}}"></script>
    <script type="text/javascript" src="{{asset('core-plus-theme/vendors/datatables/js/dataTables.bootstrap.js')}}"></script>
    <script type="text/javascript" src="{{asset('core-plus-theme/js/custom_js/datatables_custom.js')}}"></script>
    <!-- end page js -->
@endsection

resources/views/admin/subcategories/show.blade.php
@extends('layouts.admin.default')

@section('title', 'Subcategoría')
@section('styles')
    <link rel="stylesheet" type="text/css" href="{{asset('core-plus-theme/css/custom_css/dashboard1.css')}}" />
@stop
@section('content')
    <!-- Content Header (Page header) -->
    <header class="header-page">
        <div class="header-data">
            <h1>@yield('title') <small> - Ver </small></h1>
        </div>
    </header>
    <article class="content">
        <div class="panel">
            <div class="panel-heading clearfix">
                <div class="pull-right text-center">               
                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal-delete">Eliminar</button>
                    <a href="{{route('subcategories.index', $subcategory[0]->id)}}" type="button" class="btn btn-warning">Atrás</a>  
                    <a href="{{route('subcategories.edit', $subcategory[0]->id)}}" type="button" class="btn btn-primary">Editar</a>
                </div>
            </div>
            <div class="panel-body">
                <div class="col-sm-12 col-md-6">
                     <ul class="panel-list">
                        <li>
                            <p><b>Nombre</b></p>
                            <p class="text-capitalize">{{ $subcategory[0] -> name }}</p>
                        </li>    
                        <li>
                            <p><b>Descripción</b></p>
                            <p class="text-capitalize">{{ $subcategory[0] -> description }}</p>
                        </li>       
                        <li>
                            <p><b>Slug</b></p>
                            <p class="text-capitalize">{{ $subcategory[0] -> slug }}</p>
                        </li>       
                    </ul>
                </div>
                <div class="col-sm-12 col-md-6">
                     <ul class="panel-list">                        
                        <li>
                            <p><b>Categoría</b></p>
                            <p class="text-capitalize">{{ $subcategory[0] -> category }}</p>
                        </li> 
                        <li>
                            <p><b>Estatus</b></p>
                            <p>@if ( $subcategory[0] -> status == 1) <span class="label label-success">Activo</span> @else <span class="label label-danger">Inactivo</span> @endif</p>
                        </li> 
                        <li class="col-xs-12 col-sm-6">
                            <p><b>Creación</b></p>
                            <p>{{ date_format($subcategory[0] -> created_at, 'd/m/Y') }}</p>
                        </li>   
                        <li class="col-xs-12 col-sm-6">
                            <p><b>Modificación</b></p>
                            <p>{{ date_format($subcategory[0] -> updated_at, 'd/m/Y') }}</p>
                        </li>             
                    </ul>
                </div>
            </div>
        </div>
    </article>
@stop
@section('modals')
    <!-- Modal -->
    <div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="modal-delete">
        <form action="{{ route('subcategories.destroy', $subcategory[0]->id) }}" method="POST"> 
            {{ csrf_field() }}
            <input type="hidden" name="_method" value="DELETE">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Eliminar Subcategoria</h4>
                    </div>
                    <div class="modal-body">     
                        <p>¿Esta seguro de eliminar la Subcategoria <b>{{ $subcategory[0] -> name}}</b>?</p>               
                    </div>
                    <div class="modal-footer text-center">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-danger">Eliminar</button>
                    </div>
                </div>
            </div>            
        </form>
    </div>
    <!-- end modal -->
@endsection