routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::middleware('auth')->group(function(){
    // Rutas Web
	Route::get('/',                 			'WebController@index');
    Route::get('/directory',					'Web\DirectoryController@index')->name('directory');
    Route::post('/directory',					'Web\DirectoryController@search')->name('directory.search');
    Route::post('/directory/filter',		'Web\DirectoryController@filter')->name('directory.filter');
    Route::get('/ranking',						'Web\RankingController@index')->name('ranking');
    Route::get('/programs',						'Web\ProgramController@index');
    Route::get('/programs/{id}',				'Web\ProgramController@show');
    Route::get('/contact',						'WebController@contact');
    Route::get('/mall/product/{id}',          	'Web\StoreController@product') -> name('store.product');
    Route::get('/mall/market/{market}',         'Web\StoreController@market') -> name('store.market');
    Route::get('/mall/{category}',             	'Web\StoreController@category') -> name('store.category');
    Route::get('/mall/{category}/{subcategory}','Web\StoreController@subcategory') -> name('store.subcategory');
	Route::get('/mall',             			'Web\StoreController@index') -> name('store.index');
	Route::post('/mall',             			'Web\StoreController@filter') -> name('store.filter');
	Route::get('/shopping/branches/{branch_id}','WebController@branchCart');

	//Others routes
	Route::get('/politics', function() {
	    return view('web.others.politics');
	});
	Route::get('/terms', function() {
	    return view('web.others.terms');
	});
	Route::get('/faq', function() {
	    return view('web.others.faq');
	});

	//My account routes
	Route::get('/my-account/orders',      'Web\MyAccountController@orders')->name('my-account.orders');
    Route::get('/my-account/orders/{id}',      'Web\MyAccountController@order')->name('my-account.order');
    Route::post('/my-account/change-image/{id}',      'Web\MyAccountController@changeImage')->name('my-account.change-image');
    Route::get('/my-account/configuration',      'Web\MyAccountController@configuration')->name('my-account.configuration');
    Route::post('/my-account/change-password',      'Web\MyAccountController@changePassword')->name('my-account.change-password');
	Route::post('/my-account/edit-branch',      'Web\MyAccountController@updateBranch')->name('my-account.edit-branch');
    Route::get('/my-account',      'Web\MyAccountController@index')->name('my-account.index');
	Route::post('/my-account',      'Web\MyAccountController@update')->name('my-account.update');
	Route::post('/my-account/imessages/response/destroy',      'Web\MessageController@responseDestroy')->name('response.destroy');
	Route::post('/my-account/imessages/response/{id}',      'Web\MessageController@response')->name('imessage.response');
	Route::resource('/my-account/imessages',      'Web\MessageController');


    //Cart routes
    Route::get('/shopping',        	'Web\CartController@show')->name('cart.show');
    Route::post('/shopping/add-product/{id}',        	'Web\CartController@add')->name('cart.add');
    Route::get('/shopping/delete-product/{id}',        	'Web\CartController@delete')->name('cart.delete');
    Route::post('/shopping/update-products',        	'Web\CartController@update')->name('cart.update');
    Route::post('/shopping/destroy',        	'Web\CartController@destroy')->name('cart.destroy');
    Route::post('/shopping/order',        	'Web\CartController@generateOrder')->name('cart.order');

});


Route::prefix('admin')->group( function(){
	Route::post('/images/destroy', 						'Admin\AdminController@imageDestroy')->name('images.destroy');
	Route::post('/images/update', 						'Admin\AdminController@imageUpdate')->name('images.update');
	Route::get('/login',					'Admin\LoginController@showLoginForm')->name('admin.login');
	Route::post('/login',					'Admin\LoginController@login')->name('admin.login.submit');
	Route::post('/logout',					'Admin\LoginController@logout')->name('admin.logout');
	Route::post('password/email',					'Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
	Route::get('password/reset',					'Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
	Route::post('password/reset',					'Admin\ResetPasswordController@reset');
	Route::get('password/reset/{token}',	'Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');

	Route::middleware('auth:user')->group(function(){

		Route::post('/profile/change-password', 'Admin\ProfileController@changePassword')->name('profile.change-password');
		Route::get('/lists/state/{id}', 		'Admin\ListController@getState');
		Route::get('/lists/city/{id}', 			'Admin\ListController@getCity');
		Route::post('guides/store/{id}',     	'Admin\GuideController@store')->name('guides.store');
		Route::get('/', 						'Admin\AdminController@index')->name('admin.dashboard');
		Route::get('/logs', 					'\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
		Route::get('/objetives/create/{id}',    'Admin\ObjetiveController@newcreate');
		Route::get('/products/create/{id}',     'Admin\ProductController@newCreate');
		Route::post('/members/import',          'Admin\MemberController@import')->name('members.import');
		Route::get('/members/filter',      		'Admin\MemberController@filter')->name('members.filter');
		Route::post('/departments/import',		'Admin\DepartmentController@import')->name('departments.import');
		Route::post('/branches/import',     	'Admin\BranchController@import')->name('branches.import');
		Route::get('/transactions/filter',      'Admin\TransactionController@filter')->name('transactions.filter');
		Route::post('/payload/insert-file',      	'Admin\PayloadController@InsertFile')->name('payload.insert_file');
        Route::get('/payload/filter',      		'Admin\PayloadController@filter')->name('payload.filter');
        Route::post('/groups/filter',      		'Admin\GroupController@filter')->name('groups.filter');
		Route::get('/orders/filter',      		'Admin\OrderController@filter')->name('orders.filter');
		Route::put('/orders/status/{id}',       'Admin\OrderController@status')->name('orders.status');
		Route::get('/orders/refund-create/{id}','Admin\OrderController@refund_create')->name('orders.refund-create');
		Route::post('/orders/refund-store/{id}','Admin\OrderController@refund_store')->name('orders.refund-store');
		Route::get('/accounts/filter/{id}',     'Admin\AccountController@filter')->name('accounts.filter');
		Route::get('/programs/filter',          'Admin\ProgramController@filter')->name('programs.filter');
		Route::get('/picking',          'Admin\PickingController@index');
		Route::get('/reports',          'Admin\ReportController@index');
		Route::get('/reports/inventory-output',          'Admin\ReportController@inventoryOutput');
		Route::get('/reports/exchange-item',          'Admin\ReportController@exchangeItem');
		Route::get('/reports/exchange-user',     'Admin\ReportController@exchangeUser');
		Route::get('/reports/exchange-item/filter',   'Admin\ReportController@exchangeFilter')->name('exchange-item.filter');
		Route::get('/reports/exchange-user/filter',   'Admin\ReportController@exchangeUserFilter')->name('exchange-user.filter');
		Route::get('/reports/contribution-exchange',   'Admin\ReportController@reportContributionAndExchange');
		Route::get('/reports/contribution-exchange/filter',   'Admin\ReportController@reportContributionAndExchangeFilter')->name('contribution-exchange.filter');
		Route::get('/reports/inventory-output/filter',          'Admin\ReportController@inventoryOutputFilter')->name('reports.inventory-output.filter');
		Route::resource('/consolidated',        'Admin\AccountController');
		Route::resource('/transactions',        'Admin\TransactionController');
		Route::resource('/payload',             'Admin\PayloadController');
		Route::resource('/accounts',            'Admin\AccountController');
		Route::post('/profile/image-change/{id}',		'Admin\ProfileController@imageChange');
		Route::resource('/profile',				'Admin\ProfileController');
		Route::resource('/users', 				'Admin\UserController');
		Route::resource('/roles', 				'Admin\RoleController');
		Route::resource('/clubs', 				'Admin\ClubController');
		Route::resource('/brands', 		  		'Admin\BrandController');
		Route::resource('/categories', 			'Admin\CategoryController');
		Route::resource('/subcategories', 		'Admin\SubcategoryController');
		Route::resource('/offers', 				'Admin\OfferController');
		Route::resource('/affiliates', 			'Admin\AffiliateController');
		Route::resource('/parents-products', 	'Admin\ParentProductController');
		Route::resource('/inventory', 			'Admin\InventoryController');
		Route::resource('/products', 			'Admin\ProductController');
		Route::resource('/agents', 				'Admin\AgentController');
		Route::resource('/orders', 				'Admin\OrderController');
		Route::resource('/programs', 			'Admin\ProgramController');
		Route::resource('/groups', 				'Admin\GroupController');
		Route::resource('/objetives', 			'Admin\ObjetiveController');
		Route::resource('/members', 			'Admin\MemberController');
		Route::resource('/branches',     		'Admin\BranchController');
		Route::resource('departments',     		'Admin\DepartmentController');
		Route::post('/messages/change-status',      'Admin\MessageController@updateStatus')->name('message.change-status');
		Route::post('/messages/response/destroy',      'Admin\MessageController@responseDestroy')->name('responses.destroy');
		Route::post('/messages/response/{id}',      'Admin\MessageController@response')->name('message.response');

app/Models/Category.php
<?php

namespace Meritop\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'categories';

    protected $fillable = [
        'id', 'name', 'description', 'slug', 'status',
    ];

    public function  subcategory()
    {
      return $this->hasmany(Subcategory::class);
    }

    public function  offer()
    {
      return $this->hasmany(Offer::class);
    }
}

resources/views/admin/categories/create.blade.php
@extends('layouts.admin.default')

@section('title', 'Categoría')
@section('styles')
    <link rel="stylesheet" type="text/css" href="{{asset('core-plus-theme/css/custom_css/dashboard1.css')}}" />
@stop
@section('content')
    <!-- Content Header (Page header) -->
    <header class="header-page">
        <div class="header-data">
            <h1>@yield('title') <small>- Crear</small></h1>
        </div>
    </header>
	<article class="content">
        <form id="form-validation"  action="{{ route('categories.store') }}" method="POST" enctype="multipart/form-data">
        {{ csrf_field() }}
        @include('layouts.form-errors')
			<div class="panel">
               <div class="panel-heading clearfix">
                    <div class="pull-right text-center">
                        <a href="{{route('categories.index')}}" type="button" class="btn btn-warning">Atrás</a>
                        <button type="submit" class="btn btn-success">Aceptar</button>
                    </div>
                </div>
                <div class="panel-body row">
                    <div class="col-sm-12 col-md-12">
                        <div class="form-group">
                            <label for="name" class="control-label">Nombre <span class="text-danger">*</span></label>
                            <input name="name" type="text" class="form-control" id="name" placeholder="Nombre" required="required">
                        </div>
                        <div class="form-group">
                            <label for="description" class="control-label">Descripción <span class="text-danger">*</span></label>
                            <textarea name="description" class="form-control" id="description" placeholder="Descripcion" required="required" rows="10"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="image" class="control-label">Imagen <span class="text-danger">*</span></label>
                            <input name="image" type="file" class="form-control" id="image" placeholder="Url de Imagen">
                        </div>
                        <div class="form-group">
                            <label for="slug" class="control-label">Slug <span class="text-danger">*</span></label>
                            <input name="slug" type="text" class="form-control" id="slug" placeholder="Slug" required="required">
                        </div>
                        <div class="form-group">
                            <label for="estatus" class="control-label">Estatus <span class="text-danger">*</span></label>
                            <select id="status" name="status" class="form-control" data-bv-field="status" required="required">
                                <option value="">Seleccione un estatus...</option>
                                <option value="1">Activo</option>
                                <option value="0">Inactivo</option>
                            </select>
                        </div>
                    </div>
                </div>
            </div>
        </form>
	</article>
@stop
@section('scripts')
    <!-- page js -->
    <script type="text/javascript" src="{{asset('core-plus-theme/vendors/datatables/js/jquery.dataTables.js')}}"></script>
    <script type="text/javascript" src="{{asset('core-plus-theme/vendors/datatables/js/dataTables.bootstrap.js')}}"></script>
    <script type="text/javascript" src="{{asset('core-plus-theme/js/custom_js/datatables_custom.js')}}"></script>
    <!-- end page js -->
    <!-- page js -->
    <script type="text/javascript" src="{{asset('core-plus-theme/vendors/bootstrapvalidator/js/bootstrapValidator.min.js')}}"></script>
    <script type="text/javascript" src="{{asset('core-plus-theme/vendors/bootstrap-maxlength/js/bootstrap-maxlength.js')}}"></script>
    <script type="text/javascript" src="{{asset('core-plus-theme/customs/form-validator.js')}}"></script>
    <!-- end page js -->
@endsection

resources/views/admin/categories/edit.blade.php
@extends('layouts.admin.default')

@section('title', 'Categoría')
@section('styles')
    <link rel="stylesheet" type="text/css" href="{{asset('core-plus-theme/css/custom_css/dashboard1.css')}}" />
@stop
@section('content')
    <!-- Content Header (Page header) -->
    <header class="header-page">
        <div class="header-data">
            <h1>@yield('title') <small>- Editar</small></h1>
        </div>
    </header>
	<article class="content">
        <form id="form-validation" action="{{ route('categories.update',$category -> id) }}" method="POST" enctype="multipart/form-data">
            {{ csrf_field() }}
            @include('layouts.form-errors')
            <input name="_method" type="hidden" value="PUT">
			<div class="panel">
                <div class="panel-heading clearfix">
                   <div class="pull-right text-center">
                        <a href="{{route('categories.show', $category -> id) }}" type="button" class="btn btn-warning">Atrás</a>
                        <button type="submit" class="btn btn-success">Aceptar</button>
                    </div>
                </div>
                <div class="panel-body row">
                    <div class="col-sm-12 col-md-7">
                        <div class="form-group">
                            <label for="name" class="control-label">Nombre <span class="text-danger">*</span></label>
                            <input name="name" type="text" class="form-control" id="name" placeholder="Nombre" value="{{$category -> name}}" required="required">
                        </div>
                        <div class="form-group">
                            <label for="description" class="control-label">Descripción <span class="text-danger">*</span></label>
                            <textarea name="description" class="form-control" id="description" placeholder="Descripcion"" required="required" rows="10">{{ $category -> description }}</textarea>
                        </div>
                        <div class="form-group">
                            <label for="slug" class="control-label">Slug <span class="text-danger">*</span></label>
                            <input name="slug" type="text" class="form-control" id="slug" placeholder="Slug" required="required" placeholder="Nombre" value="{{$category -> slug}}">
                        </div>
                        <div class="form-group">
                            <label for="estatus" class="control-label">Estatus <span class="text-danger">*</span></label>
                            <select id="status" name="status" class="form-control" data-bv-field="status" required="required">
                                <option value="">Seleccione un estatus...</option>
                                <option value="1" @if($category -> status == 1 ) selected="selected" @endif>Activo</option>
                                <option value="0" @if($category -> status == 0 ) selected="selected" @endif>Inactivo</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-12 col-md-5">
                        <div class="form-group">
                            <div class="text-center thumbnail relative mbl" >
                                @if (empty($image -> image))
                                    <img class="image-thumbnail max-size" src="{{ Storage::disk('images') -> url('img-default.png') }}" alt="{{ $category -> name }}">
                                @else
                                    <div class="overlay">
                                        <div class="btns">
                                            <button type="button" class="img-product btn btn-danger btn-xs" data-toggle="modal" data-target="#delete-image"><i class="fa fa-close"></i></button>
                                        </div>
                                    </div>
                                    <img class="image-thumbnail max-size" src="{{ $_ENV['STORAGE_PATH'].$image -> image }}" alt="{{ $category -> name }}">
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="image" class="control-label">Imagen </label>
                            <input id="image" name="image" type="file" class="form-control">
                            @if (!empty($image))
                                <input name="id_image" type="hidden" class="form-control" readonly="readonly" value="{{ $image -> id }}">
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </form>
	</article>
@stop
@section('modals')
    <!-- Modal delete image  -->
        @if (!empty($image))
        <!-- Modal -->
        <div class="modal fade" id="delete-image" tabindex="-1" role="dialog" aria-labelledby="delete-image">
            <form action="{{ route('images.destroy') }}" method="post">
                {{ csrf_field() }}
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Eliminar imagen</h4>
                        </div>
                        <div class="modal-body">
                            <p>¿Esta seguro de eliminar la imagen <b>{{ $category -> image }}</b>?</p>
                            <input id="id" name="id" type="hidden" value="{{ $image -> id }}">
                        </div>
                        <div class="modal-footer text-center">
                            <button type="button" class="btn btn-warning" data-dismiss="modal">No</button>
                            <button type="submit" class="btn btn-danger">Si</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <!-- end Modal -->
    @endif
    <!-- End -->
@stop
@section('scripts')
    <!-- page js -->
    <script type="text/javascript" src="{{asset('core-plus-theme/vendors/datatables/js/jquery.dataTables.js')}}"></script>
    <script type="text/javascript" src="{{asset('core-plus-theme/vendors/datatables/js/dataTables.bootstrap.js')}}"></script>
    <script type="text/javascript" src="{{asset('core-plus-theme/js/custom_js/datatables_custom.js')}}"></script>
    <!-- end page js - ->
@endsection

resources/views/admin/categories/index.blade.php
@extends('layouts.admin.default')

@section('title', 'Categorías')
@section('styles')
    <link rel="stylesheet" type="text/css" href="{{asset('core-plus-theme/css/custom_css/dashboard1.css')}}" />
    <link rel="stylesheet" type="text/css" href="{{ asset('core-plus-theme/vendors/datatables/css/dataTables.bootstrap.css') }}"/>
@stop
@section('content')
    <!-- Content Header (Page header) -->
    <header class="header-page">
        <div class="header-data">
            <h1>@yield('title') <small>- Gestiones</small></h1>
        </div> 
    </header>
    @include('flash::message')
	<article class="content">
		<div class="panel filterable">
            <div class="panel-heading clearfix">
                <h3 class="panel-title pull-left m-t-6">
                </h3>
                <div class="pull-right">
                    <a href="{{ route('categories.create')}}" class="btn btn-success btn-md" id="addButton">Nuevo</a>
                </div>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-hover datatable-asc" >
                        <thead>
                        <tr>
                            <th>Nombre</th>
                            <th>Slug</th>
                            <th>Estatus</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($categories as $datos)
                        <tr>
                            <td class="text-capitalize"><a href="{{route('categories.show',$datos -> id)}}">{{$datos -> name}}</a></td>
                            <td class="text-capitalize">{{$datos -> slug}}</td>
                            <td>@if ( $datos -> status == 1) <span class="label label-success">Activo</span> @else <span class="label label-danger">Inactivo</span> @endif</td>
                        </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
	</article>
@stop
@section('scripts')
    <!-- page script -->
    <script type="text/javascript" src="{{asset('core-plus-theme/vendors/datatables/js/jquery.dataTables.js')}}"></script>
    <script type="text/javascript" src="{{asset('core-plus-theme/vendors/datatables/js/dataTables.bootstrap.js')}}"></script>
    <script type="text/javascript" src="{{asset('core-plus-theme/js/custom_js/datatables_custom.js')}}"></script>
    <!-- end page script -->
@endsection

resources/views/admin/categories/show.blade.php
@extends('layouts.admin.default')

@section('title', 'Categoría')
@section('styles')
    <link rel="stylesheet" type="text/css" href="{{asset('core-plus-theme/css/custom_css/dashboard1.css')}}" />
@stop
@section('content')
    <!-- Content Header (Page header) -->
    <header class="header-page">
        <div class="header-data">
            <h1>@yield('title') <small>- Ver</small></h1>
        </div>
    </header>
    <article class="content">
        <div class="panel">
            <div class="panel-heading clearfix">
                <div class="pull-right text-center">
                    <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal-delete">Eliminar</button>
                    <a href="{{route('categories.index')}}" type="button" class="btn btn-warning">Atrás</a>
                    <a href="{{route('categories.edit', $category->id)}}" type="button" class="btn btn-primary">Editar</a>
                </div>
            </div>
            <div class="panel-body">
                <div class="col-md-6">
                     <ul class="panel-list">
                        <li>
                            <p><b>Nombre</b></p>
                            <p class="text-capitalize">{{ $category -> name }}</p>
                        </li>
                        <li>
                            <p><b>Descripción</b></p>
                            <p class="text-capitalize">{{ $category -> description }}</p>
                        </li>
                        <li>
                            <p><b>Slug</b></p>
                            <p class="text-capitalize">{{ $category -> slug }}</p>
                        </li>
                        <li>
                            <p><b>Estatus</b></p>
                            <p>@if ( $category -> status == 1) <span class="label label-success">Activo</span> @else <span class="label label-danger">Inactivo</span> @endif</p>
                        </li>
                        <li class="col-xs-12 col-sm-6">
                            <p><b>Fecha de creación</b></p>
                            <p>{{ date_format($category -> created_at, 'd/m/Y h:i:s A') }}</p>
                        </li>
                        <li class="col-xs-12 col-sm-6">
                            <p><b>Fecha de modificación</b></p>
                            <p>{{ date_format($category -> updated_at, 'd/m/Y h:i:s A') }}</p>
                        </li>
                    </ul>
                </div>
                <div class="col-md-6">
                    <div class="from-group">
                        <div class="text-center thumbnail mbl">
                            @if (empty($image -> image))
                                <img  class="image-thumbnail max-size" src="{{ Storage::disk('images') -> url('img-default.png') }}" alt="{{ $category -> name }}">
                            @else
                                <img  class="image-thumbnail max-size" src="{{ $_ENV['STORAGE_PATH'].$image -> image }}" alt="{{ $category -> name }}">
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </article>
@stop
@section('modals')
    <!-- Modal -->
    <div class="modal fade" id="modal-delete" tabindex="-1" role="dialog" aria-labelledby="modal-delete">
        <form action="{{ route('categories.destroy', $category-> id) }}" method="POST">
            {{ csrf_field() }}
            <input type="hidden" name="_method" value="DELETE">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Eliminar Categoría</h4>
                    </div>
                    <div class="modal-body">
                        <p>¿Esta seguro de eliminar la Categoría <b>{{ $category -> name}}</b>?</p>
                    </div>
                    <div class="modal-footer text-center">
                        <button type="button" class="btn btn-warning" data-dismiss="modal">Atrás</button>
                        <button type="submit" class="btn btn-danger">Eliminar</button>
                    </div>
                </div>
            </div>
        </form>
    </div>
@stop
@section('scripts')
    <!-- page js -->
    <script type="text/javascript" src="{{asset('core-plus-theme/vendors/datatables/js/jquery.dataTables.js')}}"></script>
    <script type="text/javascript" src="{{asset('core-plus-theme/vendors/datatables/js/dataTables.bootstrap.js')}}"></script>
    <script type="text/javascript" src="{{asset('core-plus-theme/js/custom_js/datatables_custom.js')}}"></script>
    <!-- end page js-->
@endsection